### PR TITLE
Upgrade containerd to fix cve issues

### PR DESCRIPTION
**Pull request by pugangxa**
Signed-off-by: Gang Pu <pugangxa@cn.ibm.com>

See https://github.com/fybrik/helm/pull/32#issuecomment-1097672233
Since there's issues for master branch(https://github.com/helm/helm/pull/10630), do it based on 3.7.2 release.

@revit13 Please help review, thanks.

### CODE REVIEW

**Comment by roytman** [comment]
Hi @pugangxa , thanks for your PR, we are going to eliminate this repository and use upstream helm.

**Comment by pugangxa** [comment]
> Hi @pugangxa , thanks for your PR, we are going to eliminate this repository and use upstream helm.

Good, it make sense.  Do we have a timeframe when this will be done?

**Comment by roytman** [comment]
> Good, it make sense. Do we have a timeframe when this will be done?

The PR https://github.com/fybrik/fybrik/pull/1441 has been submitted, so it will be done very soon.

**Comment by roytman** [comment]
@pugangxa I'm merging this PR in order to create a new release of Fybrik (v0.6.6). The PR https://github.com/fybrik/fybrik/pull/1441 will be part of Fybrik v0.7.0

**Comment by pugangxa** [comment]
> @pugangxa I'm merging this PR in order to create a new release of Fybrik (v0.6.6). The PR [fybrik/fybrik#1441](https://github.com/fybrik/fybrik/pull/1441) will be part of Fybrik v0.7.0

Thanks very much, we need release v0.6.6 urgently!

**Comment by pugangxa** [comment]
I found it does now work now since containerd also depend on opentelemetry and the version is old, but we depend on a new version with breaking changes by opa.

**Pull request merged**
